### ISSUE TITLE
issue with threex.domevents (linkify.js)

### ISSUE THREAD

**Issue by antitoyz** [jeromeetienne/threex.domevents#14]
Hi Iam using last version of three.js.
I am strugling to make linkify work, but I don't succed.
 
you can find my code here : 
http://stackoverflow.com/questions/35303666/three-js-dom-event-linkify-js

can somebody help ?

**Comment by MasterJames** [comment]
+1

**Comment by weiserhei** [comment]
I have written a post on SO for a quick solve, but the source should be updated. 
Also, the raycaster code in the DomEvents is ancient, its about time for a refresh @jeromeetienne :)

**Comment by jeromeetienne** [comment]
hmm i would be happy to help but dont get it. im using this threex.domevent everyday without issue. 

can you guys elaborate ?

**Comment by weiserhei** [comment]
Ive created a PR #15 which includes the update to r74 and some simpler raycaster code. This is my first PR so please let me know if I should change something.

**Comment by jeromeetienne** [comment]
thanks for this PR

**Comment by antitoyz** [comment]
everything is fine . it works. If you can explain (in detail) what was the problem, please do. 
you save me. thank you a lot .
