### ISSUE TITLE
Uncaught TypeError: THREEx.DomEvents is not a constructor

### ISSUE THREAD

**Issue by ohmygod481999** [jeromeetienne/threex.domevents#30]
![image](https://user-images.githubusercontent.com/42038296/77230287-bfdecb00-6bc5-11ea-9688-9a3908e14d6b.png)

**Comment by u97bn** [comment]
Hello, I'm working on a threejs project and tried to add some threex but i got the same error as you doing this : `const domEvent = new THREEx.DomEvent(camera, renderer.domElement);` 
I'd be happy to know how did you figured it out ?

**Comment by alzC** [comment]
+1 on vue.js app,  install package with npm

**Comment by thekubilay** [comment]
hello, I encountered same problem on vue 3. already installed it via npm and imported it like below.

```
//@ts-ignore
import THREEx from "threex.domevents/threex.domevents.js"

const domEvents = new THREEx.DomEvents(this.camera, this.renderer.domElement)
```

but still this giving me "not a constructor" error.
