### ISSUE TITLE
Use THREEx in an Angular Project

### ISSUE THREAD

**Issue by liuzzom** [jeromeetienne/threex.domevents#31]
Hi.
I'm trying to use this library in an Angular project (you can find the code [here](https://github.com/liuzzom/waldo-front-end) ). I installed the library using `npm install --save threex.domevents` but I can't import in my .ts file. I tried to use `import {THREEx} from 'threex.domevents'` but it does not work.

I also tried to download the `threex.domevents.js` file from this repository and use it. I can do the import but it seems that the event listeners that I add don't work.

How can I import and use the library into the project? Thanks

**Comment by Martvse** [comment]
Did you solve this problem?

**Comment by jehangir001** [comment]
I have same issue, Do any one solved this problem?
